name: Changelog

on: [push, pull_request]

jobs:
  build:
    name: Changelog
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.CHANGELOG_TOKEN }}